// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQD4zCPI4NILl887Aek5WCpx9TOXFE0YM',
    appId: '1:736454868443:web:b7d3b30c121af573f97bfe',
    messagingSenderId: '736454868443',
    projectId: 'blood-searcher',
    authDomain: 'blood-searcher.firebaseapp.com',
    storageBucket: 'blood-searcher.appspot.com',
    measurementId: 'G-E1ZVVREDYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnzsCCg2Z6qwWQP9BeeJNceDRtH6SiLcs',
    appId: '1:736454868443:android:52aed7a115022d10f97bfe',
    messagingSenderId: '736454868443',
    projectId: 'blood-searcher',
    storageBucket: 'blood-searcher.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjEZmm6Kxt4in4iFznk7h8tN-5Tv2S_-4',
    appId: '1:736454868443:ios:c3035fa8a835c6c9f97bfe',
    messagingSenderId: '736454868443',
    projectId: 'blood-searcher',
    storageBucket: 'blood-searcher.appspot.com',
    iosBundleId: 'com.example.bloodsearcher',
  );
}
